
--------THERE IS A LAPTOP PRODUCTION HAPPENS AT WORLD WIDE LEVEL AND IT HAS TO BE DISTRIBUTED AMONGST THE COUNTRIES. 
--------HOWEVER THE CHALLENGE HERE IS THAT, THEY DON’T HAVE RIGHT PROPORTION TO DISTRIBUTE THE UNITS TO THE RESPECTIVE COUNTRIES
--===========================================================================================================================================================================
-------------------------------------------------------------ROLE OF AN ANALYST-------------------------------------------------------------------------------
--========TO GET THE RIGHT PROPORTION AT COUNTRY LEVEL AND HERE ARE THE STEP BY STEP APPROACH NEEDS TO BE DONE IN GIVEN DATA AND SQL PROGRAMMING

--IMPORT TABLE

USE TEST_SQL
SELECT * FROM PRODUCT_COUNTRY_SALES;
SELECT * FROM PRODUCTION_TABLE;

--=================STEP - 2 ==========================
--GET A SUMMARY TABLE AS
--PRODUCT_COUNTRY_LEVEL_YEARLY_SALES FROM TABLE-PRODUCT_COUNTRY_SALES


SELECT
PRODUCT,
COUNTRY,
TRANSACTION_YEAR,
UNITS	
FROM PRODUCT_COUNTRY_SALES
GROUP BY PRODUCT,COUNTRY,TRANSACTION_YEAR,UNITS;

--=================STEP -3 ==========================

--GET A SUMMARY TABLE AS
--PRODUCT_COUNTRY_AVG_SALES

SELECT
PRODUCT,
COUNTRY,
AVG(UNITS) AS AVG_UNITS
FROM PRODUCT_COUNTRY_SALES
GROUP BY PRODUCT,COUNTRY,UNITS;

--=================STEP -4 ==========================
----GET A SUMMARY TABLE AS
----PRODUCT_COUNTRY_MARKET_SHARE

SELECT
PRODUCT,
COUNTRY,
SUM(UNITS) AS TOTAL_UNITS
FROM PRODUCT_COUNTRY_SALES
GROUP BY PRODUCT,COUNTRY;


SELECT
A.PRODUCT,
A.COUNTRY,
AVG(UNITS) AS AVG_UNITS,
FORMAT(A.UNITS/B.TOTAL_UNITS,'P0') AS MARKET_SHARE
--INTO PROD_COUNT
FROM PRODUCT_COUNTRY_SALES AS A
LEFT JOIN 
( SELECT 
	PRODUCT,
	COUNTRY,
	SUM(UNITS) AS TOTAL_UNITS
FROM PRODUCT_COUNTRY_SALES 
GROUP BY PRODUCT,COUNTRY) AS B
ON 
A.PRODUCT=B.PRODUCT
GROUP BY A.PRODUCT,A.COUNTRY,B.TOTAL_UNITS,A.UNITS;


--=================STEP -5 ==========================
--------MERGE PRODUCT_COUNTRY_MARKET_SHARE TO PRODUCTION TABLE 
--------PRODUCT_COUNTRY_MARKET_SHARE TO PRODUTION_TABLE

SELECT
A.PRODUCT,
A.TRANSACTION_YEAR,
B.PRODUCTION_UNITS
FROM PRODUCT_COUNTRY_SALES AS A
LEFT JOIN
PRODUCTION_TABLE AS B
ON 
A.PRODUCT=B.PRODUCT;


SELECT * FROM PRODUCTION_TABLE;

SELECT
PRODUCT,
PRODUCTION_UNITS
FROM PRODUCTION_TABLE
GROUP BY PRODUCT,PRODUCTION_UNITS;

SELECT
A.PRODUCT,
A.COUNTRY,
A.AVG_UNITS,
A.MARKET_SHARE,
B.TOTAL_PROD
FROM PROD_COUNT AS A 
LEFT JOIN 
(SELECT
PRODUCT,
SUM(PRODUCTION_UNITS) AS TOTAL_PROD
FROM PRODUCTION_TABLE
GROUP BY PRODUCT ) AS B 
ON 
A.PRODUCT=B.PRODUCT
GROUP BY A.PRODUCT,A.COUNTRY,A.AVG_UNITS,A.MARKET_SHARE,B.TOTAL_PROD;